steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - europe-west3-docker.pkg.dev/$PROJECT_ID/tg-birthdays/tg-bdays-bot:$TAG_NAME
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - europe-west3-docker.pkg.dev/$PROJECT_ID/tg-birthdays/tg-bdays-bot:$TAG_NAME

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - tg-bdays
      - --image
      - europe-west3-docker.pkg.dev/$PROJECT_ID/tg-birthdays/tg-bdays-bot:$TAG_NAME
      - --region
      - europe-west3
      - --platform
      - managed

images:
  - europe-west3-docker.pkg.dev/$PROJECT_ID/tg-birthdays/tg-bdays-bot:$TAG_NAME

options:
  logging: CLOUD_LOGGING_ONLY
