alter table public.users
    add column if not exists google_email text,
    add column if not exists google_subject text,
    add column if not exists google_refresh_token text,
    add column if not exists google_access_token text,
    add column if not exists google_token_expires_at timestamptz,
    add column if not exists google_sync_enabled boolean not null default false,
    add column if not exists google_last_synced_at timestamptz,
    add column if not exists google_sync_error text;

alter table public.birthdays
    add column if not exists id bigint generated by default as identity,
    add column if not exists birth_day smallint,
    add column if not exists birth_month smallint,
    add column if not exists birth_year smallint,
    add column if not exists source text not null default 'manual',
    add column if not exists external_contact_id text,
    add column if not exists google_contact_etag text,
    add column if not exists created_at timestamptz not null default timezone('utc', now()),
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'birthdays'
          and column_name = 'owner'
    ) then
        alter table public.birthdays rename column owner to user_id;
    end if;
end $$;

do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'birthdays'
          and column_name = 'name'
    ) then
        alter table public.birthdays rename column name to display_name;
    end if;
end $$;

delete from public.birthdays
where birthday is null
   or birthday !~ '^\d{2}/\d{2}$';

update public.birthdays
set
    birth_day = nullif(split_part(birthday, '/', 1), '')::smallint,
    birth_month = nullif(split_part(birthday, '/', 2), '')::smallint
where birthday is not null
  and (birth_day is null or birth_month is null);

alter table public.birthdays
    alter column birth_day set not null,
    alter column birth_month set not null,
    alter column display_name set not null,
    alter column user_id set not null;

do $$
begin
    if exists (
        select 1
        from pg_constraint
        where conname = 'birthdays_pkey'
    ) then
        alter table public.birthdays drop constraint birthdays_pkey;
    end if;

    if exists (
        select 1
        from pg_constraint
        where conname = 'birthdays_name_key'
    ) then
        alter table public.birthdays drop constraint birthdays_name_key;
    end if;

    alter table public.birthdays add constraint birthdays_pkey primary key (id);
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'birthdays_source_check'
    ) then
        alter table public.birthdays
            add constraint birthdays_source_check check (source in ('manual', 'google'));
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'birthdays_day_check'
    ) then
        alter table public.birthdays
            add constraint birthdays_day_check check (birth_day between 1 and 31);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'birthdays_month_check'
    ) then
        alter table public.birthdays
            add constraint birthdays_month_check check (birth_month between 1 and 12);
    end if;

    if not exists (
        select 1
        from pg_constraint
        where conname = 'birthdays_year_check'
    ) then
        alter table public.birthdays
            add constraint birthdays_year_check check (birth_year is null or birth_year between 1900 and 9999);
    end if;
end $$;

create index if not exists birthdays_user_day_idx
    on public.birthdays (user_id, birth_month, birth_day);

create unique index if not exists birthdays_google_contact_idx
    on public.birthdays (user_id, external_contact_id)
    where external_contact_id is not null;

create unique index if not exists birthdays_manual_name_idx
    on public.birthdays (user_id, display_name, source);

alter table public.birthdays
    drop column if exists birthday;
